### PR TITLE
Make game restartable

### PR DESCRIPTION
**Pull request by jameshi16**
This commit makes the game restartable.

### CODE REVIEW

**Comment by floofywork** [comment]
it looks good to me. kotge you look over this rq

**Comment by Robotino04** [comment]
Clicking the "menu" button gives me a "Attempt to call function 'null::_on_mouse_clicked (Callable)’ on a null instance." error on "scripts/global/global.gd:69 - at function: _process" for both clients. Probably have to clear `mouse_input_functions` when changing scenes.

**Comment by jameshi16** [comment]
> Clicking the "menu" button gives me a "Attempt to call function 'null::_on_mouse_clicked (Callable)’ on a null instance." error on "scripts/global/global.gd:69 - at function: _process" for both clients. Probably have to clear `mouse_input_functions` when changing scenes.

Hi, that should have been done with `_on _tree_exiting` on `Card.gd` and `Slot.gd`. Is there potentially a race condition 😞

**Comment by Robotino04** [comment]
It happens consistently for me so hopefully not. Did this work for you?

**Comment by jameshi16** [comment]
> It happens consistently for me so hopefully not. Did this work for you?

Yep, I can't replicate it consistently. I'll check around a bit

**Comment by Robotino04** [comment]
Works perfectly now. I think this also resolves the "Multiple games without restarting client" TODO.

**Comment by floofywork** [comment]
@Robotino04 can we merge this now or no?

**Comment by Robotino04** [comment]
> @Robotino04 can we merge this now or no?
> 

imo yes, but you wanted Kotge to have a look. But seeing as they don't have time rn, I'll merge it.

**Pull request merged**
